name: Ora Startup Check

on:
  push:
  pull_request:

jobs:
  check-ui-startup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Run Ora startup check
      run: python startup_check.py

    - name: Run UI module import check
      run: python startup_check_ui.py 