program: Mecca
area: Sales and Marketing
domains:
  - mecca.com.au
keywords:
  - RSVP
  - event
  - creative
projects:
  - Event Coordination
  - Creative Approvals
contacts:
  - alice@mecca.com.au
  - bob@mecca.com.au
  - mecca@mecca.com.au 