program: Retail Expansion
area: Business Development
domains:
  - retail.ailo.com
  - expansion.ailo.com
keywords:
  - store opening
  - new market
  - site visit
projects:
  - New Store Launch
  - Market Research
contacts:
  - name: Sarah Lee
    email: sarah.lee@retail.ailo.com
  - name: Tom Nguyen
    email: tom.nguyen@expansion.ailo.com
  - name: Expansion Alias
    email: expansion@ailo.com 